// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.4.0.0
//      SpecFlow Generator Version:3.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace hp_kata
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class EstimatePurchaseV4Feature : object, Xunit.IClassFixture<EstimatePurchaseV4Feature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "EstimatePurchaseV4.feature"
#line hidden
        
        public EstimatePurchaseV4Feature(EstimatePurchaseV4Feature.FixtureData fixtureData, hp_kata_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "", "EstimatePurchaseV4", "\tIn order to buy harry potter books\r\n\tAs a customer\r\n\tI want to estimate the valu" +
                    "e of my purchase", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Estimate the value of three books of different volumes")]
        [Xunit.TraitAttribute("FeatureTitle", "EstimatePurchaseV4")]
        [Xunit.TraitAttribute("Description", "Estimate the value of three books of different volumes")]
        [Xunit.TraitAttribute("Category", "V4")]
        public virtual void EstimateTheValueOfThreeBooksOfDifferentVolumes()
        {
            string[] tagsOfScenario = new string[] {
                    "V4"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Estimate the value of three books of different volumes", null, tagsOfScenario, argumentsOfScenario);
#line 7
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
 testRunner.Given("a basket", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Price",
                            "Volume"});
                table1.AddRow(new string[] {
                            "8",
                            "1"});
                table1.AddRow(new string[] {
                            "8",
                            "2"});
                table1.AddRow(new string[] {
                            "8",
                            "2"});
#line 9
 testRunner.When("I buy books", ((string)(null)), table1, "When ");
#line hidden
#line 14
 testRunner.Then("the total is 23.199999999999999 €", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Estimate the value of 5 books forming 2 sets of different volumes")]
        [Xunit.TraitAttribute("FeatureTitle", "EstimatePurchaseV4")]
        [Xunit.TraitAttribute("Description", "Estimate the value of 5 books forming 2 sets of different volumes")]
        [Xunit.TraitAttribute("Category", "V4")]
        public virtual void EstimateTheValueOf5BooksForming2SetsOfDifferentVolumes()
        {
            string[] tagsOfScenario = new string[] {
                    "V4"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Estimate the value of 5 books forming 2 sets of different volumes", null, tagsOfScenario, argumentsOfScenario);
#line 17
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 18
 testRunner.Given("a basket", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Price",
                            "Volume"});
                table2.AddRow(new string[] {
                            "8",
                            "1"});
                table2.AddRow(new string[] {
                            "8",
                            "2"});
                table2.AddRow(new string[] {
                            "8",
                            "3"});
                table2.AddRow(new string[] {
                            "8",
                            "2"});
                table2.AddRow(new string[] {
                            "8",
                            "3"});
#line 19
 testRunner.When("I buy books", ((string)(null)), table2, "When ");
#line hidden
#line 26
 testRunner.Then("the total is 36.799999999999997 €", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Estimate the value of 5 forming 3 sets of different volumes")]
        [Xunit.TraitAttribute("FeatureTitle", "EstimatePurchaseV4")]
        [Xunit.TraitAttribute("Description", "Estimate the value of 5 forming 3 sets of different volumes")]
        [Xunit.TraitAttribute("Category", "V4")]
        public virtual void EstimateTheValueOf5Forming3SetsOfDifferentVolumes()
        {
            string[] tagsOfScenario = new string[] {
                    "V4"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Estimate the value of 5 forming 3 sets of different volumes", null, tagsOfScenario, argumentsOfScenario);
#line 29
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 30
 testRunner.Given("a basket", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Price",
                            "Volume"});
                table3.AddRow(new string[] {
                            "8",
                            "1"});
                table3.AddRow(new string[] {
                            "8",
                            "2"});
                table3.AddRow(new string[] {
                            "8",
                            "1"});
                table3.AddRow(new string[] {
                            "8",
                            "2"});
                table3.AddRow(new string[] {
                            "8",
                            "1"});
#line 31
 testRunner.When("I buy books", ((string)(null)), table3, "When ");
#line hidden
#line 38
 testRunner.Then("the total is 38.399999999999999 €", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                EstimatePurchaseV4Feature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                EstimatePurchaseV4Feature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
